config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'
  resources :recipes, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cooking_time.rb
class CookingTime < ActiveHash::Base
    self.data = [
      { id: 1, name: '---' },
      { id: 2, name: '10分以下' },
      { id: 3, name: '20分' },
      { id: 4, name: '30分' },
      { id: 5, name: '1時間' },
      { id: 6, name: '1時間30分' },
      { id: 7, name: '2時間以上' }
    ]

    include ActiveHash::Associations
    has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :user
    belongs_to :cooking_time

    has_one_attached :image

    validates :image, presence: true
    validates :name, presence: true
    validates :cooking_time_id, presence: true, numericality: { other_than: 1 }
    validates :food, presence: true
    validates :cooking_method, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    has_many :recipes

    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

    validates :nickname, presence: true

    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
    validates :password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @recipes = Recipe.all
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    def recipe_params
        params.require(:recipe).permit(:image, :name, :cooking_time_id, :food, :cooking_method).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&family=M+PLUS+Rounded+1c:wght@300&family=Noto+Sans+JP:wght@300&family=Oswald:wght@700&family=Rampart+One&family=Roboto:wght@100&family=Space+Grotesk:wght@700&family=Work+Sans:ital,wght@0,500;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= render "shared/header" %>

<main>
    <div class="main-container">
        <div class="main-top">
            <div class="main-top-text">
                <p>自分のレシピを投稿しよう！</p>
            </div>
            <div class="swiper-container">
                <div class="swiper infinite-slider">
                    <div class="swiper-wrapper">
                    <div class="swiper-slide"><%= image_tag 'recipe1.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe2.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe3.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe4.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe5.jpeg' %></div>
                </div>
            </div>
        </div>

        <div class="main-area">
            <div class="recipes-area">
                <div class="recipes-list-text">
                    <h2>レシピ一覧</h2>
                </div>
                <ul class="recipe-lists">
                    <% @recipes.each do |recipe| %>
                        <li class="recipe-list">
                            <div class="image-content">
                                <%= image_tag recipe.image, class: "recipe-image" %>
                            </div>
                            <div class="recipe-texts">
                                <p class="recipe-name"><%= recipe.name %></p>
                                <p class="cooking-time">調理時間目安：<%= recipe.cooking_time[:name] %></p>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</main>
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

app/views/recipes/new.html.erb
<%= render "shared/second-header" %>

<div class="recipe-post-container">
    <%= form_with model: @recipe, class: 'recipe-post-form', local: true do |f| %>
        <div class="recipe-post-main">
            <div class="recipe-post-top">
                <h1>レシピ情報入力</h1>
            </div>
            <div id="preview"></div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">料理写真<span class="indispensable">(必須)</span></p>
                <%= f.file_field :image, id:"recipe-image" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">料理名<span class="indispensable">(必須)</span></p>
                <%= f.text_area :name, class:"recipe-name-text", id:"recipe-name", maxlength:"40" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">調理時間<span class="indispensable">(必須)</span></p>
                <%= f.collection_select(:cooking_time_id, CookingTime.all, :id, :name, {}, {class:"select-box", id:"cooking_time"}) %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">材料<span class="indispensable">(必須)</span></p>
                <%= f.text_area :food, class:"food-text", id:"food" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">作り方<span class="indispensable">(必須)</span></p>
                <%= f.text_area :cooking_method, class:"cooking-method-text", id:"cooking-method" %>
            </div>

            <div class="btn-area">
                <div class="recipe-post">
                    <%= f.submit "投稿" ,class:"recipe-post-btn" %>
                </div>
                <div class="back">
                    <%=link_to '戻る', root_path, class:"back-btn" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
    <div class="header-container">
        <div class="header-left">
            <h1><%= link_to 'RandomRecipe', "#", class: "app-title" %></h1>
        </div>
        <div class="header-right">
            <ul>
                <% if user_signed_in? %>
                    <li><%= link_to current_user.nickname, "#", class: "nickname" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout" %></li>
                <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
                <% end %>
            </ul>
            <div class="recipes-create"><%= link_to 'レシピ投稿', new_recipe_path, class: "recipes-create-btn" %></div>
        </div>
    </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
    <div class="second-header-container">
        <h1><%= link_to 'RandomRecipe', root_path, class: "app-title" %></h1>
    </div>
</header>